services:
  # consumer:
  #   build: 
  #     context: ./HelloWorld/Consumer
  #     target: Development
  #   volumes:
  #     - type: bind
  #       target: /src
  #       source: ./HelloWorld/Consumer
    # depends_on:
      # my-rabbit:
      #   condition: service_healthy
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: ./HelloWorld/Consumer
  # producer:
  #   build: 
  #     context: ./HelloWorld/Producer
  #     target: Development
    # depends_on:
      # my-rabbit:
      #   condition: service_healthy
  my-rabbit:
    image: rabbitmq:3-management
    hostname: some-rabbit
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5